theme = "modern"
icons = "awesome"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "a8703b67ce240f2905287468d989f756", city_id = "2147714", units = "metric" }

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
interval = 5
use_bits = false
speed_min_unit = "M"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "cpu"
interval = 1
per_core = true

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%R %a %d/%m"

## theme = "slick"
#icons = "awesome"

#[theme]
#file = "/home/deepak/.config/i3status-rust/palenight.toml"

#[[block]]
#block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "a8703b67ce240f2905287468d989f756", city_id = "2147714", units = "metric" }

#[[block]]
#block = "net"
#device = "wlp2s0"
#format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
#interval = 5
#use_bits = false
#speed_min_unit = "M"

#[[block]]
#block = "docker"
#interval = 2
#format = "{running}/{total}"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

#[[block]]
#block = "cpu"
#interval = 1
#format = "{barchart} {utilization}% {frequency}GHz"

#[[block]]
#block = "cpu"
#interval = 1
#per_core = true

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "sound"

#[[block]]
#block = "time"
#interval = 60
#format = "%R %a %d/%m"
